### ISSUE TITLE
HAL Links: related list for People Active Here (from 1135) - frontend 34

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#50]
### **Problem Description**
Add a related list for People Active Here 

### **Expected Behavior**
Expose an accordion with the proper data for People Active Here. Will behave/look like other related list accordions. 

**Places** 
This will provide/confirm the backend query that will allow the people active here HAL link to be created.

**Implementation** 
Provide this query in ML for the HAL link:
https://lux-front-dev.collections.yale.edu/view/results/people?q=%7B%22activeAt%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fplace%2Fd8c3e262-187a-40f3-843f-cf618aefde4a%22%7D%7D

### **Needed For**
[ Add related list for People Active Here (from 1745) #34 ]( https://github.com/project-lux/lux-frontend/issues/34)

### **UAT examples**

- https://lux.collections.yale.edu/view/place/d8c3e262-187a-40f3-843f-cf618aefde4a
- https://lux.collections.yale.edu/view/results/people?q=%7B%22activeAt%22%3A%7B%22name%22%3A%22Malibu%22%7D%7D

**Comment by ar2674** [comment]
@clarkepeterf 
From yesterday's conversation HAL links should only be a ML ticket when we need to add a feature/query to create them, correct? Since we already have that feature/query [from what I am remembering yesterday] and  @jffcamp created https://github.com/project-lux/lux-middletier/issues/19, should this issue be closed ? 

Please correct me if I am wrong, I am going off my notes from yesterday's meeting. Thanks,

**Comment by prowns** [comment]
closing per note above.  There is a middle tier ticket for this.
