### ISSUE TITLE
Configuration Updates to improve searching for works about objects/works in Advanced Search 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#74]
**Problem Description:**
Need a ML advanced search configuration update to allow for searching objects/works that are about a given object/work.

**Expected Behavior/Solution:**
To support https://github.com/project-lux/lux-frontend/issues/29. 

Note:
New triples will be named:

`lux:about_or_depicts_work`
`lux:about_or_depicts_object`
**Requirements:**
- Improve searching for objects/works about objects/works in AS 
- support FE issue 29 (linked above) 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] ~Wireframe/Mockup - Mike~
- [x] ~Committee discussions - Sarah~
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [x] ~Frontend requirements- TBD~
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
Works about works:

- https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22aboutWork%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Ftext%2F5ad5d97a-1b16-42c4-ad5e-145b2371643b%22%7D%7D
- https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22aboutWork%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Ftext%2F2bc1c5a0-0085-449f-bf60-ca685d72f128%22%7D%7D%5D%7D
- https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22aboutWork%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Ftext%2F7ae0fcb3-41c5-400e-be63-337b70536dff%22%7D%7D%5D%7D

Works about objects:
-https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22aboutItem%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fobject%2F00094eda-4d0c-4d77-b676-8bda6b3c37f9%22%7D%7D

Object that is subject of a work:

- https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22subjectOfItem%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Ftext%2F4a0a53e4-c8d5-4fff-8c00-bf3d1e10b4fc%22%7D%7D

Work that is the subject of a work:

- https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22subjectOfWork%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Ftext%2F29b98ec5-b8c9-405e-a83f-03e2eb5a427b%22%7D%7D

**Dependencies/Blocks:**
- Blocking: https://github.com/project-lux/lux-frontend/issues/29

**Related Github Issues:**
Meta: https://github.com/project-lux/lux-frontend/issues/14
- https://github.com/project-lux/lux-marklogic/issues/64 (dupe, will need to close if re-appears) 

**Related links:**

- These links can consist of resources, bugherds, etc.

~**Wireframe/Mockup:**~
~Place wireframe/mockup for the proposed solution at end of ticket.~

**Comment by roamye** [comment]
Dupe of https://github.com/project-lux/lux-marklogic/issues/64. Need to close #64 once github unbans ar2674

**Comment by clarkepeterf** [comment]
@roamye  @prowns I think this ticket is well formed. The triples are named in the ticket and are available in the data. UAT can be done through the frontend

**Comment by roamye** [comment]
@clarkepeterf - how can this ticket be moved forward? is it OK to put it on the 08/05 or 08/19 milestone? unsure of the level of effort for this tix but it is blocking [FE 29 ](https://github.com/orgs/project-lux/projects/1/views/16?pane=issue&itemId=54178292)

**Comment by clarkepeterf** [comment]
@kkdavis14  I believe both of the triples originate from works, is that correct?

`lux:about_or_depicts_work` is for works about other works?
and `lux:about_or_depicts_object` is for works about objects?

**Comment by kkdavis14** [comment]
@clarkepeterf correct, potentially coming from Linguistic Objects, Visual Items or Sets.

**Comment by clarkepeterf** [comment]
@kamerynB this can be implemented as a hopWithField search term:

### First create new indexes

You'll need to update the index config to add new `workAboutWorkId` and `workAboutItemId` indexes. You can model these off of the existing `workAboutConceptId`, `workAboutPlaceId`, `workAboutAgentId` indexes.

### Next create a hopWithField search term

Here is an existing hopWithField search term:
```
    aboutConcept: {
      patternName: 'hopWithField',
      predicates: ['lux("about_or_depicts_concept")'],
      targetScope: 'concept',
      hopInverseName: 'subjectOfConcept',
      indexReferences: ['conceptPrimaryName'],
    },
```
Some info about all of these properties:

- The property containing the object (`aboutConcept`) is the name of the search term. I'm guessing we would call the new fields `aboutWork` and `aboutItem`.

- `patternName` is the name of the pattern, which will be 'hopWithField'

- `predicates` should be set to the name of the triple for that field (e.g. `'lux("about_or_depicts_work")'` - it accepts an array of predicates but we should only need an array with one predicate

- `targetScope` should be the scope of the child search term (in this case 'item' or 'work')

- `hopInverseName` gives the name of the search term for the inverse search term (if this is searching for Works that are about Objects, the inverse term is searching for Objects that have a Work about them) - in order for them to match the other inverse terms, I think they should be called `subjectOfObject` and `subjectOfWork` - I would argue that really every inverse term should just be called `subjectOf`, since they are all in different scopes. If you decide to do this you'd have to change the userFacingConfig for these terms and the `conceptsSubjectsForExhibition` query in the middle tier as well. I'll leave that up to you to decide.

- `indexReferences` is used to get the name of the target scope (so should be `itemPrimaryName` or `workPrimaryName` for each field)

- `idIndexReferences` - the other work `about*` fields don't have this property right now, but we should add it. This allows the search pattern to match documents by the field indexes rather than through triples. This will use your new fields `workAboutWorkId` or `workAboutItemId`. If you wouldn't mind adding the already existing indexes to the other search terms that would be great : (`workAboutConceptId`, `workAboutPlaceId`, `workAboutAgentId`

### Then update userFacingConfig

You should also update the userFacingConfig for your hopWithField search terms and their inverse terms

**Comment by kamerynB** [comment]
@clarkepeterf Thank you Peter! I will get started on this then.

**Comment by prowns** [comment]
UAT - Keep open until FE ticket is deployed.

**Comment by clarkepeterf** [comment]
@prowns I don't think any work needs to be done on the frontend. I have a comment about this in the frontend ticket: https://github.com/project-lux/lux-frontend/issues/29#issuecomment-2302487569

**Comment by clarkepeterf** [comment]
Yes, and I believe this can be approved. I just moved example queries into the UAT for this ticket.

**Comment by roamye** [comment]
Looks good in prod. Closing

**Comment by brent-hartwig** [comment]
@clarkepeterf and @roamye, I believe this ticket introduced the following five search terms, within the `work` search scope, plus their Hop Inverse search terms spread over multiple search scopes:

1. aboutAgent
2. aboutConcept
3. aboutItem
4. aboutPlace
5. aboutWork

I encountered a configuration error which is easy to address and likely not noticed if the scope of this ticket was just to support these in advanced search.  The configuration error could have become a problem if any of these were wired up as facets.  Each of these terms' `idIndexReferences` property value should be an array, not a string.  Here's an example of one as a string:

```javascript
    aboutAgent: {
      patternName: 'hopWithField',
      predicates: ['lux("about_or_depicts_agent")'],
      targetScope: 'agent',
      hopInverseName: 'subjectOfAgent',
      indexReferences: ['agentPrimaryName'],
      idIndexReferences: 'workAboutAgentId',
    },
```

I noticed when attempting to use https://github.com/project-lux/lux-marklogic/blob/main/scripts/generateIndexConf/indexComparisonChecks.js.

Please advise.  Thank you.

**Comment by clarkepeterf** [comment]
@brent-hartwig Only `aboutItem` and `aboutWork` were added, but the other fields were missing idIndexReferences, so were updated. However, you are correct, they should be an array. Since the app is currently functioning as expected I say we put a fix in the next release

**Comment by roamye** [comment]
I agree with a fix for next release. @clarkepeterf - can you make a separate ticket for this issue?

**Comment by clarkepeterf** [comment]
Making a ticket now

**Comment by clarkepeterf** [comment]
@roamye I made a new ticket here: https://github.com/project-lux/lux-marklogic/issues/301
